### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by VikasAggarwal** [FBoucher/TinyBlazorAdmin#16]
index.html gives the following error:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://xxxxxxxxx.z20.web.core.windows.net/_framework/wasm/dotnet.3.2.0-preview5.20216.1.js' with computed SHA-256 integrity 'jM5hce+cJKdngTUxMSXwqnnGvibwtf+QbWtu1yMCt/s='. The resource has been blocked.

I have checked the deployment steps multiple times. Not able to figure out what's wrong.

**Comment by FBoucher** [comment]
Could it be the CORS from the Azure Functions?
