### ISSUE TITLE
Deployment Failure.

### ISSUE THREAD

**Issue by dirrcher** [FBoucher/TinyBlazorAdmin#19]
Get this error when clicking on the deploy button:

There was an error downloading the template from URI 'https://raw.githubusercontent.com/FBoucher/AzUrlShortener/master/deployment/azureDeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

Wasn't "master" renamed to "main" ?

**Comment by FBoucher** [comment]
it should be fix now. 
I renamed the branch MAIN instead of master... check your version
