### ISSUE TITLE
Deployment Instructions for Connecting to Function Unclear (v2)

### ISSUE THREAD

**Issue by lukaslangrock** [FBoucher/TinyBlazorAdmin#24]
I am trying to setup AzurlShortener v2 but I am stuck at conencting the TinyBlazorAdmin SWA to the function via AD.
Mind you I am still a noob when it comes to AD only tried it out once, so I am totally inexperienced when it comes to it. Sorry if I might have missed an obvious step thats common knowledge.

I followed the [deployment.md](https://github.com/FBoucher/TinyBlazorAdmin/blob/main/deployment.md) instructions but found a few things unclear and couldn't get the authentication to work.

**1.** For the App Registration for the front end, you didn't specify the callback URL we should use for it, tbut in your [screenshot](https://github.com/FBoucher/TinyBlazorAdmin/blob/main/medias/tokensaccess.png) it sais *"Redirect URIs: 1"*. If you leave it blank then you just get an error when trying to login *"No reply address is registered for the application"*.

I then copied the callback URL from functions App-Registration but this didn't work either as I got the error *"The reply URL specified in the request does not match the reply URLs configured for the application"*. This made me look at the request URL in my browser and I could make out the string "<static-admin-interface-url>/authentication/login-callback" which just resulted in a 404 when being plugged in as the callback URI in the App-Registration.

**2.** At the end you instruct us to fill it out with the *"AD app to use"*, which I assume is the frontend AD app but it would be nice of you to write it down, this can be a bit confusing. Also would be nice to note that the x's in the `Authority` field should be the Tenant-ID because not everyone will know what to replace it with, I hope this is even correct because I wasn't really sure either.

**Comment by DamienCalvert** [comment]
I can't get this to work no matter what I try in the Redirect URI.

Could you help with what the value should be?

**Comment by lukaslangrock** [comment]
Thank you! I tried this when I opened the issue but it didn't work. probably made a typo or got something wrong but now it works. ✔

**Comment by lukaslangrock** [comment]
For anyone who sees a 404 page after clicking login too, try using Edge (Chromium) or other Chromium based browsers.

With Firefox I always get the 404, probably because of how it handles the login popup, the blazor site is not loaded and since the actual callback url seems to be not "real" and just available when the blazor app is loaded, the login fails.
