### ISSUE TITLE
Screenshots images missing on TinyBlazorAdmin deployment.md page

### ISSUE THREAD

**Issue by fs366e2spm** [FBoucher/TinyBlazorAdmin#44]
There are a few images missing (not displayed) in the manual deployment description:
https://github.com/FBoucher/TinyBlazorAdmin/blob/main/deployment.md

Examples:
- ![Creating swa][swa_create1]
- ![Creating swa part 2][swa_create2]
- ![Creating swa part 3][swa_create3]
- ![RegisterClientApp][RegisterClientApp]
- ![swa_URL][swa_URL]
- ![azFunction_CORS][azFunction_CORS]

**Comment by FBoucher** [comment]
FIxed in dev coming up soon

**Comment by FBoucher** [comment]
Look like the only one missing now is

![RegisterClientApp][RegisterClientApp]

**Comment by FBoucher** [comment]
fixed
