### ISSUE TITLE
Adding Custom Tutorial link with Error 404

### ISSUE THREAD

**Issue by heyvoon** [FBoucher/TinyBlazorAdmin#62]
![image](https://user-images.githubusercontent.com/3281265/112047451-998f9a80-8b4d-11eb-9bf8-7ebb4d76e1fc.png)

![image](https://user-images.githubusercontent.com/3281265/112047514-add39780-8b4d-11eb-9324-6e14a2fec615.png)

**Comment by FBoucher** [comment]
Sorry. The link is fixed now.
It was https://github.com/FBoucher/AzUrlShortener/blob/main/doc/post-deployment-configuration.md#add-a-custom-domain
