### ISSUE TITLE
[Feature request] One-click Single Sign-On from My Apps portal

### ISSUE THREAD

**Issue by jpawlowski** [FBoucher/TinyBlazorAdmin#70]
I am so much impressed by this work – definitely something I need to study in more detail how it actually works altogether :D

While I was checking this out, I noticed that the _Branding Home page URL_ of the frontend app registration is left empty:

![image](https://user-images.githubusercontent.com/75446/117074421-959d8d80-ad33-11eb-95fd-198eacac4d94.png)

Because of this, the related Enterprise App object that is created after initial login cannot be used to login with a single click from the My Apps portal:

![image](https://user-images.githubusercontent.com/75446/117074621-e01f0a00-ad33-11eb-945a-3eab172dd7e9.png)

![image](https://user-images.githubusercontent.com/75446/117074692-f7f68e00-ad33-11eb-84a3-f03e9ee7ab29.png)

One could simply add the starting page of the frontend but that doesn't login the user automatically so a click on the "Login" button is still needed.
I tried a couple of variants of the URL of the backend Azure Function application, e.g. OAuth2 endpoints but apparently had no luck. `RedirectToLogin.razor` seems to handle the redirection but simply replicating this URL and use it for Homepage URL doesn't do the trick.

I fear I am not an expert of this authentication provider stuff in Azure (yet). That's why I wanted to bring this idea into this post, maybe someone more familiar with the matter knows how to actually put this together :-)

**Comment by FBoucher** [comment]
I will close this issue. Many things changed with the last version and that should not be a problem anymore.
