### ISSUE TITLE
Tiny Blazor Admin Sign-in Issue

### ISSUE THREAD

**Issue by bseran** [FBoucher/TinyBlazorAdmin#73]
When trying to login to Tiny Blazor Admin I receive the message:

"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope user.read openid profile https://*********.azurewebsites.netuser_impersonation is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>."

**Comment by rlaplaine** [comment]
You probably just miss a / at the end of the url in the appsettings file

**Comment by FBoucher** [comment]
Try again with v3 it should be fixed.
