### ISSUE TITLE
Can't login with Firefox

### ISSUE THREAD

**Issue by mccsoft** [FBoucher/TinyBlazorAdmin#75]
Hello.
With the same user and password I can login with Chrome 91 browser but I can't do it with Firefox 89.
In Firefox I gets 404 error:
![image](https://user-images.githubusercontent.com/6916600/121529030-344d9600-ca26-11eb-877e-05168b11f3a1.png)
![image](https://user-images.githubusercontent.com/6916600/121528505-bd180200-ca25-11eb-88d5-75958587096e.png)

**Comment by xuyuji9000** [comment]
I had the same 404 problem with Firefox 94.0.2

**Comment by FBoucher** [comment]
was related to changes in AAD. Should be fixed in v3
