### ISSUE TITLE
Create App for the Azure Function

### ISSUE THREAD

**Issue by sstadelaide** [FBoucher/TinyBlazorAdmin#76]
Hello,
Under step 4- Create Azure Active Directory (AAD) Components, you have specified to Create App for the Azure Function
"We need a second App registration, this time to let the Azure Function validate that user information contained in the token is valid."
I am unable to understand how you got to this step and how you created a new app function, If I am to create a new app function then what and how am I need to do it.
![image](https://user-images.githubusercontent.com/58458284/133542023-8430dfbc-1a9a-4e82-9008-9ac5b08eda22.png)
I do not know what I need to select with the creating a new function app.

Can you please help guide. even on the video from YouTube this particular step is not very clear how you ended up creating the second function app.
https://www.youtube.com/watch?v=UaUdFSXrbmA

**Comment by Boorda** [comment]
I'm stuck here too; I have no idea how you got here. I do not see anywhere in Azure to create an App Service and I see no Authentication/Authorization section under the Function App Settings, I only get Authentication with a Managed Identity setting.
 
Anytime I try to sign in it still thinks it's linked to your git hub even though I cloned the repo and deployed the template from my own and updated the sign in to point to my repo. Could you please, please update this so I can finish implementing this project? Thanks in advance.

**Comment by jstelten** [comment]
Need help also :)

**Comment by FBoucher** [comment]
Look at the new version v3. THings should be easier.
