### ISSUE TITLE
Sign In Problem

### ISSUE THREAD

**Issue by ved-leachim** [FBoucher/TinyBlazorAdmin#80]
Hello everybody

I've followed the steps from the deployment documentation, but when I sign in I get the following error:
![image](https://user-images.githubusercontent.com/74647637/161133996-ecd3e583-d422-4afe-a8e9-03521e60dc92.png)

Microsoft says that this means that the Azure function cannot be found:
![image](https://user-images.githubusercontent.com/74647637/161130782-737e4194-9bb6-481e-ab9a-505691167445.png)

Can someone pls help here?

Thank you very much.

**Comment by FBoucher** [comment]
Should be fixed in v3
